# Generated by Django 3.1.5 on 2021-05-23 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titutlo_barra_uno', models.CharField(max_length=30)),
                ('titutlo_barra_dos', models.CharField(max_length=30)),
                ('subtitulo', models.CharField(max_length=30)),
                ('titulo_uno', models.CharField(max_length=30)),
                ('titulo_dos', models.CharField(max_length=30)),
            ],
        ),
    ]
