# Generated by Django 3.1.5 on 2021-05-23 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inicio',
            old_name='titutlo_barra_dos',
            new_name='titulo_barra_dos',
        ),
        migrations.RenameField(
            model_name='inicio',
            old_name='titutlo_barra_uno',
            new_name='titulo_barra_uno',
        ),
    ]
