# Generated by Django 3.1.5 on 2021-05-24 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210524_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acerca',
            name='inicio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acerca', to='main.inicio'),
        ),
    ]
