# Generated by Django 3.2.3 on 2021-05-24 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_contacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estilo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('resumen', models.CharField(max_length=200)),
                ('contenido', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='PresentacionEstilos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('enfasis', models.CharField(max_length=30)),
                ('contenido', models.CharField(max_length=200)),
            ],
        ),
    ]
