# Generated by Django 3.2.3 on 2021-05-25 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_estilo_presentacionestilos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('enfasis', models.CharField(max_length=30)),
                ('contenido', models.CharField(max_length=100)),
            ],
        ),
    ]
