# Generated by Django 3.2.3 on 2021-05-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_maestro_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maestro',
            name='imagen',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
